import { combineReducers } from 'redux';
import BooksReducer from './reducer_books';
import ActiveBook from './reducer_active_book';

/** app state generated by reducer functions */
const rootReducer = combineReducers({
  /** 
   * value of books is whatever is returned from the BooksReducer function 
   * on a basic level, this can be an array of objects where each object represents a book
   * here we are adding a key called books to global application state with the value of whatever BooksReducer returns
   */
  books: BooksReducer,
  activeBook: ActiveBook
});

export default rootReducer;
